Temp_String = "I am your king. "
SomeValue = 1000000.8888888

print(Temp_String * 2)
print()
print(Temp_String[2:9])
print()
print(len(Temp_String))
print()
print(Temp_String.index("am"))
print()
print("your" in Temp_String)
print()
print(Temp_String.upper())
print()
print(Temp_String.lower())
print()
print(Temp_String.rstrip())
print()
print(Temp_String.lstrip())
print()
print(Temp_String.endswith(". "))
print()
print(Temp_String.isnumeric())
print()
print(Temp_String.split())
print()
print("The value is |{vl:>5.2f}|".format(vl=SomeValue))
